version: '3.3'

networks:
  frontend:
    external: 
      name: frontend

services:
  hp:
    build: .
    container_name: hp
    command: sleep infinity
    ports:
    - 80:80
    networks: 
        - frontend

  web1_app:
    image: tutum/hello-world
    container_name: web1_app
    networks: 
        - frontend

  web2_app:
    image: tutum/hello-world
    container_name: web2_app
    networks: 
      - frontend

  web3_app:
    image: tutum/hello-world
    container_name: web3_app
    networks: 
      - frontend
    
